name: Notebooks


permissions:
  contents: read


on:
  pull_request:
    branches:
      - main


jobs:
  clean-notebooks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          # Fetch from the contributor's fork
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          # Fetch the commit SHA
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Clean Jupyter Notebooks
        uses: ResearchSoftwareActions/EnsureCleanNotebooksAction@e22cb52580930a21c3121a44c9e67fa37e149121 # v1.1
